name       : shiboken6
version    : 6.2.1
release    : 2
source     :
    - https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-6.2.1-src/pyside-setup-opensource-src-6.2.1.tar.xz : e0df6f42ed92e039d44ae9bf7d23cc4ee2fc4722c87adddbeafc6376074c4cd4
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : programming.python
summary    : Shiboken generates bindings for C++ libraries using CPython source code
description: |
    PySide6 is the official Python module from the Qt for Python project, which provides access to the complete Qt6 framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libxslt)
    - pkgconfig(python3)
    - numpy
rundeps    :
    - devel :
        - python3-devel
        - qt6-base-devel
setup      : |
    cd sources/shiboken6
    %cmake_ninja \
        -DBUILD_TESTS=OFF \
        -DUSE_PYTHON_VERSION=3 \
        -DNUMPY_INCLUDE_DIR=$(python3 -c "import site; print(site.getsitepackages()[0])")/numpy/core/include
build      : |
    cd sources/shiboken6
    %ninja_build
install    : |
    pushd sources/shiboken6
    %ninja_install
    popd

    export PATH=/usr/lib64/qt6/bin:$PATH
    python3 setup.py egg_info --build-type=shiboken6
    cp -r shiboken6.egg-info $installdir/$(python3 -c "import site; print(site.getsitepackages()[0])")
    %python3_compile $installdir/usr/lib
