name       : shiboken6
version    : 6.3.0
release    : 7
source     :
    - https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-6.3.0-src/pyside-setup-opensource-src-6.3.0.tar.xz : 9d808d617c8daa2fe074f9a481478dc923a9799b5c89f6c5af38ece111ed57e2
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : programming.python
summary    : Shiboken generates bindings for C++ libraries using CPython source code
description: |
    PySide6 is the official Python module from the Qt for Python project, which provides access to the complete Qt6 framework.
clang      : yes
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libxslt)
    - pkgconfig(python3)
    - numpy
    - python-packaging
rundeps    :
    - devel :
        - python3-devel
        - qt6-base-devel
        - python-packaging
setup      : |
    cd sources/shiboken6
    %cmake_ninja \
        -DBUILD_TESTS=OFF \
        -DUSE_PYTHON_VERSION=3 \
        -DNUMPY_INCLUDE_DIR=$(python3 -c "import site; print(site.getsitepackages()[0])")/numpy/core/include
build      : |
    cd sources/shiboken6
    %ninja_build
install    : |
    pushd sources/shiboken6
    %ninja_install
    popd

    export PATH=/usr/lib64/qt6/bin:$PATH
    python3 setup.py egg_info --build-type=shiboken6
    cp -r shiboken6.egg-info $installdir/$(python3 -c "import site; print(site.getsitepackages()[0])")
    %python3_compile $installdir/usr/lib
